import { type NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/react';
import Game from '~/components/Game';
import Faq from '~/components/Faq';

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Clinko</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.webp" />
      </Head>
      <main className="flex min-h-screen select-none flex-col items-center justify-center gap-8 bg-rich-black-blue">
        <div className="mt-8 flex h-32 w-full flex-col items-center">
          <h1 className="text-center text-6xl font-bold text-slate-200">
            Clinko
          </h1>
          <p className="w-96 text-center text-2xl font-bold text-slate-200">
            Click to collect <span className="text-green-400">millions</span>{' '}
            and <span className="text-orange-400">billions</span> and{' '}
            <span className="text-rose-400">trillions</span> of clinks!
          </p>
        </div>

        {!sessionData && (
          <button
            className="rounded-md bg-seasalt/10 py-3 px-10 font-semibold text-seasalt no-underline transition hover:bg-seasalt/20"
            onClick={() => void signIn()}
          >
            Sign In
          </button>
        )}

        {sessionData && (
          <button
            className="rounded-md bg-seasalt/10 py-3 px-10 font-semibold text-seasalt no-underline transition hover:bg-seasalt/20"
            onClick={() => void signOut()}
          >
            Sign Out
          </button>
        )}

        {sessionData && <Game />}

        <Faq />
      </main>
    </>
  );
};

export default Home;
