import { type NextPage } from 'next';
import Head from 'next/head';
import { signIn, signOut, useSession } from 'next-auth/react';
import Game from '~/components/Game';

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Clinko</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen select-none flex-col items-center justify-center gap-8 bg-rich-black-blue">
        <div className="mt-8 flex h-32 w-full flex-col items-center">
          <h1 className="text-center text-6xl font-bold text-slate-200">
            Clinko
          </h1>
          <p className="w-96 text-center text-2xl font-bold text-slate-200">
            Click to collect <span className="text-green-400">millions</span>{' '}
            and <span className="text-orange-400">billions</span> and{' '}
            <span className="text-rose-400">trillions</span> of clinks!
          </p>
        </div>
        {!sessionData && (
          <button
            className="rounded-md bg-seasalt/10 py-3 px-10 font-semibold text-seasalt no-underline transition hover:bg-seasalt/20"
            onClick={sessionData ? () => void signOut() : () => void signIn()}
          >
            {sessionData ? 'Sign out' : 'Sign In'}
          </button>
        )}
        {sessionData && (
          <button
            className="rounded-md bg-seasalt/10 py-3 px-10 font-semibold text-seasalt no-underline transition hover:bg-seasalt/20"
            onClick={() => void signOut()}
          >
            Sign Out
          </button>
        )}
        {sessionData && <Game />}

        <div className="flex max-w-3xl flex-col gap-4 pb-20 text-seasalt">
          <p className="text-3xl font-bold">FAQ</p>
          <p className="text-2xl font-bold">
            What is Clinko?{' '}
            <span className="text-xl text-cyan-700">
              A simple game where you&apos;re mean&apos;t to mostly AFK and
              build up enough points to buy buildings and upgrades!
            </span>
          </p>

          <p className="text-2xl font-bold">
            How do Buildings and Upgrades work?{' '}
            <span className="text-xl text-cyan-700">
              <br></br>- Buildings have a set number of balls per second they
              drop and as you upgrade them the balls they drop are worth more!
              <br></br>- Buildings cost points to produce balls! Every time a
              building drops a ball it costs the equivalent amount of points to
              produce that ball based on the level of that building. (A level 3
              building costs 3 points to produce a ball.)
              <br></br>- Clicking is always free and produces balls at the level
              of the Cursors building!
            </span>
          </p>

          <p className="text-2xl font-bold">
            Why was Clinko made?{' '}
            <span className="text-xl text-cyan-700">
              Primarily for learning by building a complicated web app with the
              T3 Stack consisting of Next.js, TailwindCSS, TypeScript, Prisma,
              NextAuth, tRPC, Zod, Vercel for web hosting, and PlanetScale for
              MySQL hosting.
            </span>
          </p>

          <p className="text-2xl font-bold">
            Who made Clinko?{' '}
            <span className="text-xl text-turquoise/60 hover:underline">
              <a href="https://taylorsvec.com">Taylor Svec</a>
            </span>
          </p>
        </div>
      </main>
    </>
  );
};

export default Home;
